name: Terraform Destroy

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Install dependencies
        run: npm install
      - name: Generate bindings for providers and modules
        run: cdktf get --language typescript
      - name: Run Tests
        run: npm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: myGitHubActions

      - name: Destroy
        run: cdktf destroy --auto-approve
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TF_API_TOKEN }}
